### ISSUE TITLE
crossplatform todo list

### ISSUE THREAD

**Issue by adcxyz** [aiberlin/NTMI#26]
The NTMI setup does not yet run equally fully on macOS, linux, raspberry and windows. 

Here is the current state for macOS, linux, raspi, win: 

- [x] NTMI loadscript     - mac, lin, rpi, win 
- [x] all sounds play      - mac, lin, rpi, win 
- [x] MIDI control   - mac, lin, rpi, win 
- [ ] HID control   - mac, - HIDAPI is broken on lin, rpi, win 
- [ ] login to nUFO-WiFi - mac, lin, win - broken on rpi
- [ ] OSC/nUFO works   - mac, lin, win - on rpi only via router
